export {data};

var data = [];
import {content} from "./keys/additionally.js";
data.push(content);
import {content2} from "./keys/temperature.js"
data.push(content2)
import {content3} from "./keys/spo.js";
data.push(content3);
import {content4} from "./keys/arterialPressure.js";
data.push(content4);
import {content5} from "./keys/pulse.js";
data.push(content5);
import {content6} from "./keys/venus.js";
data.push(content6);
import {content7} from "./keys/tactics.js";
data.push(content7);
import {content8} from "./keys/vrach.js";
data.push(content8);
// import {content9} from "./keys/home.js";
// data.push(content9);
// import {content10} from "./keys/mobilephone.js";
// data.push(content10);
// import {content11} from "./keys/morbi.js";
// data.push(content11);
// import {content12} from "./keys/name.js";
// data.push(content12);
// import {content13} from "./keys/otoscopy.js";
// data.push(content13);
// import {content14} from "./keys/preliminarydiagnosis.js";
// data.push(content14);
// import {content15} from "./keys/reception.js";
// data.push(content15);
// import {content16} from "./keys/recommendations.js";
// data.push(content16);
// import {content17} from "./keys/status.js";
// data.push(content17);
// import {content18} from "./keys/vitae.js";
// data.push(content18);
// import {content19} from "./keys/work.js";
// data.push(content19);
